# Generated by Django 5.1.2 on 2024-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address_number', models.IntegerField()),
                ('address_street', models.TextField()),
                ('address_apt', models.TextField()),
                ('address_zip', models.IntegerField()),
                ('dob', models.DateField()),
                ('dor', models.DateField()),
                ('party', models.TextField()),
                ('precinct', models.IntegerField()),
                ('state', models.BooleanField()),
                ('v20town', models.BooleanField()),
                ('primary', models.BooleanField()),
                ('general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
