# Generated by Django 5.1.2 on 2024-11-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='v20town',
            new_name='v21town',
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.TextField(),
        ),
    ]
