# Generated by Django 5.1.2 on 2024-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_rename_v20town_voter_v21town_alter_voter_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(),
        ),
    ]
