# Generated by Django 5.1.2 on 2024-11-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_voter_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.TextField(),
        ),
    ]
