# Generated by Django 5.1.3 on 2024-11-14 01:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheersUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('displayName', models.TextField()),
                ('phoneNumber', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('available', models.BooleanField()),
                ('basePrice', models.TextField()),
                ('category', models.TextField()),
                ('imagePath', models.TextField()),
                ('shotPrice', models.TextField()),
                ('currency', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mixer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('available', models.BooleanField()),
                ('imagePath', models.TextField()),
                ('addOnPrice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle', models.BooleanField()),
                ('shot', models.BooleanField()),
                ('drinkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.drink')),
                ('mixerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mixer')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkOrderCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('drinkOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.drinkorder')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('imagePath', models.TextField()),
                ('fastTrackCents', models.TextField()),
                ('maxConsumptionCents', models.TextField()),
                ('drinks', models.ManyToManyField(to='project.drink')),
                ('mixers', models.ManyToManyField(to='project.mixer')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('albumArtURL', models.TextField()),
                ('artistName', models.TextField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('timestamp', models.DateTimeField()),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.location')),
            ],
        ),
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('amountPaidCents', models.IntegerField()),
                ('consumerId', models.TextField()),
                ('consumerName', models.TextField()),
                ('fastTrack', models.BooleanField()),
                ('fcmToken', models.TextField(blank=True, null=True)),
                ('orderNumber', models.TextField()),
                ('phoneNumber', models.TextField()),
                ('status', models.TextField()),
                ('table', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('tip', models.TextField(blank=True, null=True)),
                ('tipCurrency', models.TextField(blank=True, null=True)),
                ('verificationCode', models.TextField()),
                ('drinkOrders', models.ManyToManyField(to='project.drinkorder')),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.location')),
                ('salePointId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.salepoint')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.location')),
                ('salePointId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.salepoint')),
            ],
        ),
    ]
