# Generated by Django 5.1.3 on 2024-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='locationId',
            field=models.TextField(),
        ),
    ]
