# Generated by Django 5.1.3 on 2024-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_music_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genres',
            field=models.TextField(),
        ),
    ]
