# Generated by Django 5.1.3 on 2024-11-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_order_consumptionorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drinkOrders',
        ),
        migrations.AddField(
            model_name='order',
            name='drinkOrderCounts',
            field=models.ManyToManyField(to='project.drinkordercount'),
        ),
    ]
