# Generated by Django 5.1.3 on 2024-11-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_order_drinkorders_order_drinkordercounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='drinkId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.drink'),
        ),
        migrations.AlterField(
            model_name='drinkorder',
            name='mixerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.mixer'),
        ),
    ]
