# Generated by Django 5.1.3 on 2024-11-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_drinkorder_drinkid_alter_drinkorder_mixerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
