# Generated by Django 5.1.3 on 2024-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheersuser',
            name='displayName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
