# Generated by Django 5.1.3 on 2024-12-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_businessuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.TextField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
