# Generated by Django 5.1.3 on 2024-12-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_music_id_alter_music_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
