# Generated by Django 5.1.3 on 2024-12-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_music_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
